parameters:
  aligent_db_tools.parameters.yml: '%kernel.project_dir%/config/parameters.yml'

services:
  aligent_db_tools.helper.db_settings:
    class: 'Aligent\DBToolsBundle\Helper\DBSettings'
    arguments:
        - '%aligent_db_tools.parameters.yml%'
  aligent_db_tools.helper.database:
    class: 'Aligent\DBToolsBundle\Helper\DatabaseHelper'
    arguments:
        - '@aligent_db_tools.helper.db_settings'

  Aligent\DBToolsBundle\Helper\Compressor\Gzip:
    public: true
  Aligent\DBToolsBundle\Helper\Compressor\Uncompressed:
    public: true
